config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :inmet_weather_data
  mount Sidekiq::Web => '/sidekiq'

  resources :users_project, only: [:index, :create, :destroy, :show] do
    patch 'update_user', to: 'users_project#update', on: :collection
    patch 'update_admin', to: 'users_project#update_admin', on: :collection
  end

  resources :noa_weather_stations do
    get 'start_import', on: :collection
  end

  resources :inmet_weather_stations do 
    get 'start_import', on: :collection
    get 'start_import_data', on: :collection
  end

  devise_for :users


  resources :dashboard do
    get 'grafico', on: :collection
  end

  resources :log_erros

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :default_filter, only: [:index]
  before_action :default_date
  before_action :data_range, only: [:index]

  def index
    respond_to do |format|
      if turbo_frame_request?
        format.html { render partial: 'data_menu'}
      else
        format.html
      end
    end

  end

  def grafico
  end

  private

  def data_range
    @data = fetch_inmet_weather_data

    if params[:amostragem] == 'Hora a Hora'
      time_to_time
    else
      diario
    end

    data_histograma
    box_plot
  end

  def data_histograma
    @temperatura_histograma = calcular_histograma(@temperatura || [], ' ºC')
    @humidade_histograma = calcular_histograma(@humidade || [], ' %')
    @chuva_histograma = calcular_histograma(@chuva || [], ' mm')
    @radiacao_histograma = calcular_histograma(@radiacao || [], ' (KJ/m¬≤)')
    @vento_histograma = calcular_histograma(@vento || [], ' m/s')
    @presao_histograma = calcular_histograma(@presao || [], ' hPa')
  end
  def box_plot
    grouped_data = @data.group_by { |t| t.hr_medicao.to_brz.to_date }
    @temperatura_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:tem_ins, grouped_data))
    @humidade_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:umd_ins, grouped_data))
    @chuva_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:chuva, grouped_data))
    @radiacao_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:rad_glo, grouped_data))
    @vento_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:ven_vel, grouped_data))
    @presao_box = calcular_limites_e_outliers(@data.fetch_and_process_data_g(:pre_ins, grouped_data))
  end

  def calcular_limites_e_outliers(dados_lista)

    resultados_data = []
    resultados_autiliers = []

    dados_lista.each do |dados_objeto|
      # Extrair os dados e a data do objeto
      dados, data = dados_objeto[0], dados_objeto[1]

      # Ordenar os dados
      sorted_data = dados.sort
      # Se n < 3, impossível calcular q1 e q3 corretamente
      return [] if sorted_data.count < 5

      # Calcular os quartis manualmente
      n = sorted_data.length
      q1_index = (n + 1) * 0.25
      q2_index = (n + 1) * 0.5
      q3_index = (n + 1) * 0.75

      q1 = sorted_data[q1_index.floor - 1] + (q1_index - q1_index.floor) * (sorted_data[q1_index.floor] - sorted_data[q1_index.floor - 1])
      q2 = sorted_data[q2_index.floor - 1] + (q2_index - q2_index.floor) * (sorted_data[q2_index.floor] - sorted_data[q2_index.floor - 1])
      q3 = sorted_data[q3_index.floor - 1] + (q3_index - q3_index.floor) * (sorted_data[q3_index.floor] - sorted_data[q3_index.floor - 1])

      # Calcular o intervalo interquartil (IQR)
      iqr = q3 - q1

      # Definir limites para identificar outliers
      lower_bound = q1 - 0.9 * iqr
      upper_bound = q3 + 0.9 * iqr

      # Identificar outliers
      outliers = dados.select { |x| x < lower_bound || x > upper_bound }

      # Formatar os dados no formato necessário para o ApexCharts
      formatted_data = {
        x: data.to_s, # Converter a data para milissegundos
        y: [lower_bound.round(2), q1.round(2), q2.round(2), q3.round(2), upper_bound.round(2)]
      }

      # Formatar os outliers
      formatted_outliers = {
        x: data.to_s, # Converter a data para milissegundos
        y: outliers
      }

      # Adicionar os dados formatados à lista de resultados
      resultados_data << formatted_data
      resultados_autiliers << formatted_outliers
    end

    # Retornar os resultados como um array de objetos Ruby
    return [resultados_data, resultados_autiliers]
  end

  def diario
    @grouped_data = @data.group_by { |t| t.hr_medicao.to_brz.to_date }

    @temperatura, @time = @data.fetch_and_process_data_m(:tem_ins, @grouped_data).transpose
    @humidade, @time    = @data.fetch_and_process_data_m(:umd_ins, @grouped_data).transpose
    @radiacao, @time    = @data.fetch_and_process_data_m(:rad_glo, @grouped_data).transpose
    @chuva, @time       = @data.fetch_and_process_data_m(:chuva,   @grouped_data).transpose
    @presao, @time      = @data.fetch_and_process_data_m(:pre_ins, @grouped_data).transpose
    @vento, @time       = @data.fetch_and_process_data_m(:ven_vel, @grouped_data).transpose
  end

  def time_to_time
    @temperatura, @time = @data.fetch_and_process_data(:tem_ins).transpose
    @humidade, @time    = @data.fetch_and_process_data(:umd_ins).transpose
    @radiacao, @time    = @data.fetch_and_process_data(:rad_glo).transpose
    @chuva, @time       = @data.fetch_and_process_data(:chuva).transpose
    @presao, @time      = @data.fetch_and_process_data(:pre_ins).transpose
    @vento, @time       = @data.fetch_and_process_data(:ven_vel).transpose
  end

  private

  def fetch_inmet_weather_data
    Time.use_zone("America/Sao_Paulo") do
      @start_time = Time.zone.parse(params[:data_inicio].to_s).beginning_of_day
      @end_time = Time.zone.parse(params[:data_fim].to_s).end_of_day
    end

    InmetWeatherDatum.filter(by_cdg_station: @cdg_station)
                     .where(hr_medicao: @start_time..@end_time)
                     .order(:hr_medicao)
  end

  def default_date
    params[:data_fim] = params[:data_fim] || Time.current.to_brz.to_date
    params[:data_inicio] = params[:data_inicio] || Time.current.to_brz.to_date
    params[:amostragem] = params[:amostragem] || 'Hora a Hora'
  end

  def default_filter
    current_user.config_system.update_attribute(:cdg_station, params[:cdg_station]) if  params[:cdg_station] && current_user.cdg_station != params[:cdg_station]

    @cidade = InmetWeatherStation.all.collect{ |t| [t.cidade, t.cdg_estacao] }.uniq
    @type_data = !(params[:type_data] == 'false')
    @cdg_station = params[:cdg_station] ||= current_user.cdg_station
  end

  def calcular_histograma(data, u_m)
    # Remova os valores zero do array
    data = data.reject { |value| value.zero? }

    # Verifique se ainda há dados restantes após a remoção dos zeros
    if data.empty?
      puts "Não há dados para calcular o histograma, pois todos os valores são zero."
      return []
    end

    if data.count <= 1
      puts "Quantidade invalida para fazer analesi de histograma"
      return []
    end

    # Calcular o número de intervalos usando a regra de Sturges
    n = data.length
    k = (1 + 3.322 * Math.log10(n)).ceil

    # Calcular a largura de cada intervalo
    data_min = data.min
    data_max = data.max
    interval_width = (data_max - data_min) / k

    # Inicializar um hash para armazenar as frequências
    histogram = Hash.new(0)

    # Criar os intervalos e contar a frequência de dados dentro de cada intervalo
    data.each do |value|
      interval_start = (value / interval_width).floor * interval_width
      interval_end = interval_start + interval_width
      interval_str = "#{interval_start.round(1)} #{u_m} - #{interval_end.round(1)} #{u_m}"

      histogram[interval_str] += 1
    end

    # Formatar os resultados como um array de hashes
    result = histogram.map { |interval, frequency| { x: interval, y: frequency } }

    # Ordenar os intervalos em ordem crescente
    result.sort_by! { |hash| hash[:x] }

    return result
  end

  def calculate_statistics(data, date)
    return nil if data.nil? || data.empty?

    data.compact!
    data.sort!

    n = data.length
    l = (n * 0.25).to_i
    u = (n * 0.75).to_i

    q1 = data[l]
    median = (data[(n - 1) / 2] + data[n / 2]) / 2.0
    q3 = data[u]

    min = data.first
    max = data.last

    { date: date, data: [min, q1, median, q3, max]}
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_box_plot.html.erb
    <div id="<%= id %>"></div>
    <script>
        var options = {
            series: [
                {
                    name: 'box',
                    type: 'boxPlot',
                    data: <%= raw dados[0].to_json %>
                },
                {
                    name: 'outliers',
                    type: 'scatter',
                    data: <%= raw dados[1].to_json %>
                }
            ],
            chart: {
                type: 'boxPlot',
                height: 350
            },
            colors: ['#008FFB', '#FEB019'],
            title: {
                text: '<%= name_x.upcase %>',
                align: 'left'
            },
            xaxis: {
            },
            tooltip: {
                shared: false,
                intersect: true
            }
        };

        var chart = new ApexCharts(document.querySelector("#<%= id %>"), options);
        chart.render();
    </script>

app/views/dashboard/_cads.html.erb
<div>
  <div class="row justify-content-center d-flex">
    <div class="card m-3" style="width: 250px;height: 126px;">
      <div class="card-body" style="text-align: center">
        <p class="mb-1 mt-3 font-weight-bold text-muted">Estações</p>
        <p class="text-success" style="font-weight: 900;font-size: 30px"><%= @size_station %></p>
      </div>
    </div>
    <div class="card m-3" style="width: 250px;height: 126px;">
      <div class="card-body" style="text-align: center">
        <p class="mb-1 mt-3 font-weight-bold text-muted">Estações Operante</p>
        <p class="text-success" style="font-weight: 900;font-size: 30px"><%= @operante %></p>
      </div>
    </div>
    <div class="card m-3" style="width: 250px;height: 126px;">
      <div class="card-body" style="text-align: center">
        <p class="mb-1 mt-3 font-weight-bold text-muted">Estações Pane</p>
        <p class="text-success" style="font-weight: 900;font-size: 30px"><%= @pane %></p>
      </div>
    </div>
    <div class="card m-3" style="width: 250px;height: 126px;">
      <div class="card-body" style="text-align: center">
        <p class="mb-1 mt-3 font-weight-bold text-muted">Dados</p>
        <p class="text-success" style="font-weight: 900;font-size: 30px"><%= @data %></p>
      </div>
    </div>

    <div class="card m-3" style="width: 250px;height: 126px;">
      <div class="card-body" style="text-align: center">
        <p class="mb-1 mt-3 font-weight-bold text-muted">Dados Tratados</p>
        <p class="text-success" style="font-weight: 900;font-size: 30px"><%= 0.0 %></p>
      </div>
    </div>
  </div>

<!--  <div class="row justify-content-center d-flex">-->



<!--  </div>-->
</div>

app/views/dashboard/_card_data.html.erb
<div class="card">
  <div class="card-body">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button style="margin-left: 10px;" class="btn btn-primary active" id="line-<%= id%>-tab" data-bs-toggle="pill" data-bs-target="#line-<%= id%>" type="button" role="tab" aria-controls="line-<%= id%>" aria-selected="true">Linha</button>
      </li>
      <li class="nav-item" role="presentation">
        <button style="margin-left: 10px;" class="btn btn-primary" id="bar-<%=id%>-tab" data-bs-toggle="pill" data-bs-target="#bar-<%=id%>" type="button" role="tab" aria-controls="bar-<%=id%>" aria-selected="false">Histograma</button>
      </li>
      <li class="nav-item" role="presentation">
        <button style="margin-left: 10px;" class="btn btn-primary" id="box-<%=id%>-tab" data-bs-toggle="pill" data-bs-target="#box-<%=id%>" type="button" role="tab" aria-controls="box-<%=id%>" aria-selected="false">BoxPlot</button>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="line-<%= id%>" role="tabpanel" aria-labelledby="line-<%= id%>-tab">
        <%= render partial: 'temp', locals: { dados: dados,
                                              time: time,
                                              id: "chats_line_#{id}",
                                              name_y: type,
                                              name_x: id,
                                              type: type,
                                              unidade: unidade } %>
      </div>
      <div class="tab-pane fade" id="bar-<%=id%>" role="tabpanel" aria-labelledby="bar-<%=id%>-tab">
        <%= render partial: 'periodo', locals: { dados: histograma,
                                                 id: "chats_histogram_#{id}",
                                                 name_y: type,
                                                 name_x: id,
                                                 type: type,
                                                 unidade: ''} %>
      </div>
      <div class="tab-pane fade" id="box-<%=id%>" role="tabpanel" aria-labelledby="box-<%=id%>-tab">
        <%= render partial: 'box_plot', locals: { dados: box_plot_data,
                                                  id: "chats_box_#{id}",
                                                  name_y: type,
                                                  name_x: id,
                                                  type: type,
                                                  unidade: unidade} %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_data_menu.html.erb
<%= turbo_frame_tag 'render_table_dashbord' do %>
  <div class="row mt-3">
    <%= render partial: 'card_data',
               locals: { dados: @temperatura || [], time: @time, id: 'TEMPERATURA', type: 'HORA' , unidade: " ºC"      ,histograma: @temperatura_histograma || [], box_plot_data: @temperatura_box || [] } %>
    <%= render partial: 'card_data',
               locals: { dados: @humidade || [],    time: @time, id: 'HUMIDADE',    type: 'HORA' , unidade: " %"       ,histograma: @humidade_histograma    || [], box_plot_data: @humidade_box || [] } %>
    <%= render partial: 'card_data',
               locals: { dados: @chuva || [],       time: @time, id: 'CHUVA',       type: 'HORA' , unidade: " mm"      ,histograma: @chuva_histograma       || [], box_plot_data: @chuva_box || [] } %>
    <%= render partial: 'card_data',
               locals: { dados: @radiacao || [],    time: @time, id: 'RADIAÇÃO',    type: 'HORA' , unidade: " (KJ/m¬≤)",histograma: @radiacao_histograma    || [], box_plot_data: @radiacao_box || [] } %>
    <%= render partial: 'card_data',
               locals: { dados: @vento || [],       time: @time, id: 'VENTO',       type: 'HORA' , unidade: " m/s"     ,histograma: @vento_histograma       || [], box_plot_data: @vento_box || [] } %>
    <%= render partial: 'card_data',
               locals: { dados: @presao || [],      time: @time, id: 'PRESSÃO',     type: 'HORA' , unidade: " hPa"     ,histograma: @presao_histograma      || [], box_plot_data: @presao_box || [] } %>
  </div>

  <div class="col-sm-12 col-xl-12 box-col-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-hover table-sm">
            <thead class="thead-dark">
            <tr>
              <th scope="col">Data - Hora (UTC -3)</th>
              <th scope="col">Radiacao </th>
              <th scope="col">Chuva </th>
              <th scope="col">Dir. Vento </th>
              <th scope="col">Vel. Vento </th>
              <th scope="col">Raj. Vento </th>
              <th scope="col">Pressao </th>
              <th scope="col">Pto Orvalho</th>
              <th scope="col">Temperatura </th>
              <th scope="col">Umidade </th>
            </tr>
            </thead>
            <tbody>
            <% @data.each do |weather_datum| %>
              <tr>
                <td><%= weather_datum.hr_medicao.to_brz.to_date_b %> - <%= weather_datum.hr_medicao.to_brz.to_time_b %></td>
                <td><%= weather_datum.rad_glo %> (KJ/m¬≤)</td>
                <td><%= weather_datum.chuva %> (mm)</td>
                <td><%= weather_datum.wind_direction_to_cardinal %></td>
                <td><%= weather_datum.ven_vel %> (m/s)</td>
                <td><%= weather_datum.ven_raj %> (m/s)</td>
                <td><%= weather_datum.pre_ins %> (hPa)</td>
                <td><%= weather_datum.pto_ins %> (C)</td>
                <td><%= weather_datum.tem_ins %> (C)</td>
                <td><%= weather_datum.umd_ins %> (%)</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/dashboard/_menu_lateral.html.erb
<nav class="sidebar" data-controller="menu">
  <header>
    <div class="image-text" style="padding-left: 10px;">
      <!-- <span class="image"><img src="logo.png" alt=""></span>-->
      <div class="text logo-text">
        <span class="name"><%= current_user.name %></span>
        <span class="profession"><%= current_user.email %></span>
      </div>
    </div>

    <i class="bi bi-layout-sidebar-inset-reverse icon toggle" data-action="click->menu#toggleSidebar"></i>
  </header>

  <div class="menu-bar">
    <div class="menu">

      <ul class="menu-links" style="padding: 0;">
        <li class="nav-link">
          <%= link_to root_path do  %>
            <i class="bi bi-stack icon"></i>
            <span class="text nav-text">Dashboard</span>
          <% end %>
        </li>

        <div data-controller="menu">
          <!-- Primeiro link e submenu -->
          <li class="nav-link">
            <a href="javascript:void(0)" class='menu_station' data-menu-target="link" data-action="click->menu#toggleSubmenu">
              <i class="bi bi-boxes icon"></i>
              <span class="text nav-text">Estações Met.</span>
              <i class="bi bi-caret-down-fill icon"></i>
            </a>
          </li>

          <div class='desable' style="padding-left: 40px;" data-menu-target="submenu">
            <li class="nav-link">
              <%= link_to inmet_weather_stations_path, style:'padding-left: 10px;' do  %>
                <span class="text nav-text">INMET</span>
              <% end %>
            </li>
          </div>

          <!-- Segundo link e submenu -->
          <li class="nav-link">
            <a href="javascript:void(0)" class='menu_station' data-menu-target="link" data-action="click->menu#toggleSubmenu">
              <i class="bi bi-boxes icon"></i>
              <span class="text nav-text">Dados Met.</span>
              <i class="bi bi-caret-down-fill icon"></i>
            </a>
          </li>
          <div class='desable' style="padding-left: 40px;" data-menu-target="submenu">
            <li class="nav-link">
              <%= link_to inmet_weather_data_path, style:'padding-left: 10px;' do  %>
                <span class="text nav-text">INMET</span>
              <% end %>
            </li>
          </div>
        </div>


        <li class="nav-link" >
          <%= link_to sidekiq_web_path, target:"_blank" do  %>
            <i class="bi bi-diagram-3-fill icon"></i>
            <span class="text nav-text">Processos</span>
          <% end if current_user.admin %>
        </li>

        <li class="nav-link" >
          <%= link_to users_project_index_path do  %>
            <i class="bi bi-person-vcard icon"></i>
            <span class="text nav-text">Usuarios</span>
          <% end if current_user.admin %>
        </li>

      </ul>
    </div>

    <div class="bottom-content">
      <li class="nav-link">
        <%= link_to log_erros_path do  %>
          <i class="bi bi-bug-fill icon"></i>
          <span class="text nav-text">Logs Erros</span>
        <% end if current_user.admin %>
      </li>
      <% if ENV.fetch("RAILS_ENV", "development") == "development"  %>
        <li class="nav-link">
          <%= link_to grafico_dashboard_index_path do  %>
            <i class="bi bi-stack icon"></i>
            <span class="text nav-text">Graficos</span>
          <% end if current_user.admin %>
        </li>
      <% end %>
      <li>
        <%= link_to destroy_user_session_path do %>
          <i class="bi bi-box-arrow-left icon"></i>
          <span class="text nav-text">Sair</span>
        <% end %>
      </li>
    </div>
  </div>

</nav>

app/views/dashboard/_periodo.html.erb
<div id="<%= id %>"></div>

<script>
    var options = {
        series: [{
            name: '<%= name_x %>',
            data: <%= raw dados.map { |data| data[:y] }.to_json %>
        }],
        chart: {
            height: 350,
            type: 'bar',
            toolbar: {
                show: false
            }
        },
        plotOptions: {
            bar: {
                borderRadius: 5,
                dataLabels: {
                    position: 'top', // top, center, bottom
                },
            }
        },
        dataLabels: {
            enabled: true,
            formatter: function (val) {
                return val + "<%= unidade %>";
            },
            offsetY: -20,
            style: {
                fontSize: '12px',
                colors: ["#304758"]
            }
        },

        xaxis: {
            categories: <%= raw dados.map { |data| data[:x] }.to_json %>,
            position: 'bottom',
            axisBorder: {
                show: false
            },
            axisTicks: {
                show: false
            },
            crosshairs: {
                fill: {
                    type: 'gradient',
                    gradient: {
                        colorFrom: '#D8E3F0',
                        colorTo: '#BED1E6',
                        stops: [0, 100],
                        opacityFrom: 0.4,
                        opacityTo: 0.5,
                    }
                }
            },
            tooltip: {
                enabled: true,
            }
        },
        yaxis: {
            axisBorder: {
                show: false
            },
            axisTicks: {
                show: false,
            },
            labels: {
                show: false,
                formatter: function (val) {
                    return val + "<%= unidade %>";
                }
            }
        },
        title: {
            text: '<%= name_x %>',
            floating: true,
            offsetY: 0,
            align: 'center',
            style: {
                color: '#444'
            }
        }
    };

    var chart = new ApexCharts(document.querySelector("#<%= id %>"), options);
    chart.render();

</script>

app/views/dashboard/_range.html.erb
<div class="col-sm-12 col-xl-12 box-col-12">
  <div class="card">
    <div class="card-body p-0">
      <div id="<%= id %>"></div>
    </div>
  </div>
</div>

<script>
    var options = {
        series: [
            {
                name: '<%= name.upcase %>',
                data: <%= raw dados %>
            }
        ],
        chart: {
            height: 350,
            type: 'line',
            dropShadow: {
                enabled: true,
                color: '#000',
                top: 18,
                left: 7,
                blur: 10,
                opacity: 0.2
            },
            toolbar: {
                show: false
            }
        },
        colors: ['#77B6EA'],
        dataLabels: {
            enabled: true,
        },
        stroke: {
            curve: 'smooth'
        },
        title: {
            text: '<%= name.upcase %>',
            align: 'left'
        },
        grid: {
            borderColor: '#e7e7e7',
            row: {
                colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
                opacity: 0.5
            },
        },
        markers: {
            size: 1
        },
        xaxis: {
            categories: <%= raw time %>,
            title: {
                text: 'Data'
            }
        },
        yaxis: {
            title: {
                text: '<%= name.upcase %>'
            },
            min: <%= (dados.min || 0) - 30 %>,
            max: <%= (dados.max || 0) + 30 %>
        },
        legend: {
            position: 'top',
            horizontalAlign: 'right',
            floating: true,
            offsetY: -25,
            offsetX: -5
        }
    };

    var chart = new ApexCharts(document.querySelector("#<%= id %>"), options);
    chart.render();
</script>

app/views/dashboard/_temp.html.erb
 <div id="<%= id %>"></div>
<script>
    var options = {
        series: [
            {
                name: '<%= name_x.upcase %>',
                data: <%= raw dados %>
            }
        ],
        chart: {
            height: 350,
            type: 'area',
            toolbar: {
                show: false
            }
        },
        colors: ['#77B6EA'],
        dataLabels: {
            enabled: true,
            formatter: function (val) {
                return val + "<%= unidade %>";
            }
        },
        stroke: {
            curve: 'straight'
        },
        title: {
            text: '<%= name_x.upcase %>',
            align: 'left'
        },
        grid: {
            borderColor: '#e7e7e7',
            row: {
                colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
                opacity: 0.5
            },
        },
        markers: {
            size: 1
        },
        xaxis: {
            categories: <%= raw (time ? time.to_json : []) %>,
            title: {
                text: '<%= type %>'
            },
            labels: {
                rotate: 0
            }

        },
        yaxis: {
            title: {
                text: '<%= name_x.upcase %>'
            },
<!--            max: <%#= (dados&.max || 0) + 10 %>,-->
            labels: {
                show: false,
                formatter: function (val) {
                    return val + "<%= unidade %>";
                }
            }
        },
        legend: {
            position: 'top',
            horizontalAlign: 'right',
            floating: true,
            offsetY: -25,
            offsetX: -5
        }
    };

    var chart = new ApexCharts(document.querySelector("#<%= id %>"), options);
    chart.render();
</script>

app/views/dashboard/grafico.html.erb
<section class="background-radial-gradient overflow-hidden">
  <div class="row" style="height: 100vh;overflow-x: auto;">
    <div class="row" style="height: 100vh; padding: 30px 10px 10px 50px">

      <%= render 'charts/apex_chats' %>

    </div>
  </div>

</section>

app/views/dashboard/index.html.erb
<section class="background-radial-gradient overflow-hidden">

  <div class="row" style="height: 100vh;overflow-x: auto;">
    <div class= 'button-active-color'>
      <div data-controller="submit-form">
        <%= form_with url: dashboard_index_path, method: :get, data: { turbo_frame: 'render_table_dashbord' } do |f| %>
          <div style="display: flex; padding: 10px; margin-left: 30px;" >
            <div style="width: 250px;">
              <%= f.label :cdg_station, "Cidade", style: 'color: white; font-size:14px' %>
              <%= f.select :cdg_station,
                           options_for_select(@cidade, params[:cdg_station]),
                           { },
                           class: 'select2 form-control',
                           style: 'important; font-size:14px',
                           id: 'subscriber-tags-select',
                           data: { 'submit-form-target': 'cdgStation' } %>
            </div>
            <div style="width: 250px; margin-left: 10px">
              <%= f.label :amostragem, "Amostragem", style: 'color: white; font-size:14px' %>
              <%= f.select :amostragem,
                           options_for_select(["Hora a Hora", "Média Diária"], params[:amostragem]),
                           { },
                           class: 'select2 form-control',
                           style: 'important; font-size:14px',
                           id: 'amostragem-select',
                           data: { 'submit-form-target': 'amostragem' } %>
            </div>
            <div style="width: 250px; margin-left: 10px;">
              <%= f.label :data_inicio, "Data de Início", style: 'color: white; font-size:14px' %>
              <%= f.date_field :data_inicio,
                               class: 'form-control',
                               style: 'height: 30px;',
                               id: 'iddataInicioField',
                               value: params[:data_inicio],
                               data: { 'submit-form-target': 'dataInicioField' } %>
            </div>
            <div style="width: 250px; margin-left: 10px">
              <%= f.label :data_fim, "Data de Fím", style: 'color: white; font-size:14px' %>
              <%= f.date_field :data_fim,
                               class: 'form-control',
                               style: 'height: 30px;',
                               id: 'iddataFimField',
                               value: params[:data_fim],
                               data: { 'submit-form-target': 'dataFimField' } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row" style="height: 100vh; padding: 30px 10px 10px 50px">
      <div class="container-fluid">
        <%= render 'data_menu' %>
      </div>
    </div>
  </div>

</section>