config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :inmet_weather_data
  mount Sidekiq::Web => '/sidekiq'

  resources :users_project, only: [:index, :create, :destroy, :show] do
    patch 'update_user', to: 'users_project#update', on: :collection
    patch 'update_admin', to: 'users_project#update_admin', on: :collection
  end

  resources :noa_weather_stations do
    get 'start_import', on: :collection
  end

  resources :inmet_weather_stations do 
    get 'start_import', on: :collection
    get 'start_import_data', on: :collection
  end

  devise_for :users


  resources :dashboard do
    get 'grafico', on: :collection
  end

  resources :log_erros

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/noa_weather_station.rb
class NoaWeatherStation < ApplicationRecord
  # includes 
  include Filterable


  # scopes 
  scope :by_cdg_estacao, ->(params) { where(cdg_estacao: params) }

  
  # methods class
  def self.inport_create(data)
    NoaWeatherStation.create(
      name:                data['name'],
      cdg_estacao:         data['id'],
      vl_altitude:         data['elevation'],
      vl_latitude:         data['latitude'],
      vl_longitude:        data['longitude'],
      datacoverage:        data['datacoverage'],
      elevationUnit:       data['elevationUnit'],
      dta_fim_operacao:    data['maxdate'],
      dta_inicio_operacao: data['mindate']
    )
  end

  def self.inport_update(obj, data)
    obj.update(
      name:                data['name'],
      cdg_estacao:         data['id'],
      vl_altitude:         data['elevation'],
      vl_latitude:         data['latitude'],
      vl_longitude:        data['longitude'],
      datacoverage:        data['datacoverage'],
      elevationUnit:       data['elevationUnit'],
      dta_fim_operacao:    data['maxdate'],
      dta_inicio_operacao: data['mindate']
    )
  end

  def self.find_create_or_update(data)
    obj = NoaWeatherStation.find_by(cdg_estacao: data['id'])
    if obj.present?
      inport_update(obj, data)
    else
      inport_create(data)
    end
  end

end

app/controllers/noa_weather_stations_controller.rb
class NoaWeatherStationsController < ApplicationController
  before_action :set_noa_weather_station, only: %i[ show edit update destroy ]
  before_action :set_filter_index, only: %i[index]

  # GET /noa_weather_stations or /noa_weather_stations.json
  def index
    @noa_weather_stations = NoaWeatherStation
                              .filter(filters_params)
                              .paginate(page: params[:page], per_page: 20)
  end

  # GET /noa_weather_stations/1 or /noa_weather_stations/1.json
  def show
  end

  # GET /noa_weather_stations/new
  def new
    @noa_weather_station = NoaWeatherStation.new
  end

  # GET /noa_weather_stations/1/edit
  def edit
  end

  # POST /noa_weather_stations or /noa_weather_stations.json
  def create
    @noa_weather_station = NoaWeatherStation.new(noa_weather_station_params)

    respond_to do |format|
      if @noa_weather_station.save
        format.html { redirect_to noa_weather_station_url(@noa_weather_station), notice: "Noa weather station was successfully created." }
        format.json { render :show, status: :created, location: @noa_weather_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @noa_weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noa_weather_stations/1 or /noa_weather_stations/1.json
  def update
    respond_to do |format|
      if @noa_weather_station.update(noa_weather_station_params)
        format.html { redirect_to noa_weather_station_url(@noa_weather_station), notice: "Noa weather station was successfully updated." }
        format.json { render :show, status: :ok, location: @noa_weather_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @noa_weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noa_weather_stations/1 or /noa_weather_stations/1.json
  def destroy
    @noa_weather_station.destroy

    respond_to do |format|
      format.html { redirect_to noa_weather_stations_url, notice: "Noa weather station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def start_import
    pages = Noa::NoaWeatherService.all_pages_stations

    for page in 1..pages
      ImportStationNoaWorker.perform_async(page) # ImportStationNoaWorker.new.perform(1) executar no console
    end

    respond_to do |format|
      format.json { render json: { message: 'Importação em Andamento.' }, status: :ok }
    end
  end

  def set_filter_index
    @station = NoaWeatherStation.all

    @wmo = @station.collect{ |t| t.cdg_estacao }.uniq
    @name = @station.collect{ |t| t.name }.uniq

    @fiters_params = filters_params
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noa_weather_station
      @noa_weather_station = NoaWeatherStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def noa_weather_station_params
      params.fetch(:noa_weather_station, {})
    end

    def filters_params
      params.permit( :by_name, :by_cdg_estacao )
    end
end

app/helpers/noa_weather_stations_helper.rb
module NoaWeatherStationsHelper
end

app/views/noa_weather_stations/_form.html.erb
<%= form_with(model: noa_weather_station) do |form| %>
  <% if noa_weather_station.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(noa_weather_station.errors.count, "error") %> prohibited this noa_weather_station from being saved:</h2>

      <ul>
        <% noa_weather_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/noa_weather_stations/_noa_weather_station.html.erb
<tr id="station_<%= noa_weather_station.id %>">
  <td><%= noa_weather_station.cdg_estacao %></td>
  <td><%= noa_weather_station.name %></td>
  <td><%= noa_weather_station.vl_latitude %></td>
  <td><%= noa_weather_station.vl_longitude %></td>
  <td><%= noa_weather_station.vl_altitude %></td>

  <td><%= noa_weather_station.dta_inicio_operacao.to_date_b %></td>
  <td><%= noa_weather_station.dta_fim_operacao.to_date_b %></td>
</tr>

app/views/noa_weather_stations/edit.html.erb
<h1>Editing noa weather station</h1>

<%= render "form", noa_weather_station: @noa_weather_station %>

<br>

<div>
  <%= link_to "Show this noa weather station", @noa_weather_station %> |
  <%= link_to "Back to noa weather stations", noa_weather_stations_path %>
</div>

app/views/noa_weather_stations/index.html.erb
<section class="background-radial-gradient overflow-hidden">

  <div style="height: 100vh;overflow-x: auto;">
    <div style="height: 100vh; padding: 30px 10px 10px 50px">

      <div>
        <div class="card">
          <div class="card-header pb-0" style="display: flex;">
            <h1>Estações Meteorológicas</h1>
            <button class='btn btn-primary btn-block' onclick= "submit_import_station()" style="margin-left: auto;margin-bottom: 11px;"> Gerar Importação </button>
          </div>
          <div class="card-body">

            <%= form_with(url: noa_weather_stations_path, method: :get) do |form| %>
              <div class="row p-4">
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Código</p>
                  <%= form.select :by_cdg_estacao,
                                  options_for_select(@wmo.collect { |tp| [tp,tp] }, @fiters_params[:by_cdg_estacao]),
                                  {include_blank: 'Selecione'},
                                  {class: 'select2 form-control'} %>
                </div>

                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Nome</p>
                  <%= form.select :by_name,
                                  options_for_select(@name.collect { |tp| [tp,tp] }, @fiters_params[:by_name]),
                                  {include_blank: 'Selecione'},
                                  {class: 'select2 form-control'} %>
                </div>


                <div class="p-1 mt-1" style="justify-content: flex-end;display: flex;">
                  <%= form.submit "Filtrar", class: 'btn btn-primary btn-block mb-1', style:'width: 179px;'%>
                </div>

              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div id="">


        <div class="card">
          <div class="card-body">

            <table class="table table-striped table-hover">
              <thead class="thead-dark">
              <tr>
                <th scope="col">Código</th> <!-- cdg_estacao -->
                <th scope="col">Cidade</th> <!-- name -->
                <th scope="col">Latitude</th> <!-- vl_latitude -->
                <th scope="col">Longitude</th> <!-- vl_longitude -->
                <th scope="col">Altitude</th> <!-- vl_altitude -->
                <th scope="col">Data Inicio</th> <!-- dta_inicio_operacao -->
                <th scope="col">Data Fim</th> <!-- dta_fim_operacao -->
              </tr>
              </thead>
              <tbody>
              <% @noa_weather_stations.each do |noa_weather_station| %>
                <%= render noa_weather_station %>
              <% end %>
              </tbody>
            </table>

            <div style="display: flex;justify-content: center;">
              <%= will_paginate @noa_weather_stations, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>


          </div>
        </div>

      </div>
    </div>
  </div>

</section>

<script>
    window.addEventListener('DOMContentLoaded', () => {
        $('.select2').select2();
    })
</script>

<script>
  function submit_import_station() {
    $.ajax({
      url: "<%= start_import_noa_weather_stations_path %>",
      type: "get",
      data: { },
      success: function (data) {
        console.log(data);
        Swal.fire({
          icon: 'success',
          title: data.message
        })
      },
      error: function (data) { },
    });
  }
</script>

app/views/noa_weather_stations/index0.html.erb
<p style="color: green"><%= notice %></p>

<h1>Noa weather stations</h1>

<div id="noa_weather_stations">
  <% @noa_weather_stations.each do |noa_weather_station| %>
    <%= render noa_weather_station %>
    <p>
      <%= link_to "Show this noa weather station", noa_weather_station %>
    </p>
  <% end %>
</div>

<%= link_to "New noa weather station", new_noa_weather_station_path %>

app/views/noa_weather_stations/new.html.erb
<h1>New noa weather station</h1>

<%= render "form", noa_weather_station: @noa_weather_station %>

<br>

<div>
  <%= link_to "Back to noa weather stations", noa_weather_stations_path %>
</div>

app/views/noa_weather_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @noa_weather_station %>

<div>
  <%= link_to "Edit this noa weather station", edit_noa_weather_station_path(@noa_weather_station) %> |
  <%= link_to "Back to noa weather stations", noa_weather_stations_path %>

  <%= button_to "Destroy this noa weather station", @noa_weather_station, method: :delete %>
</div>