config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :inmet_weather_data
  mount Sidekiq::Web => '/sidekiq'

  resources :users_project, only: [:index, :create, :destroy, :show] do
    patch 'update_user', to: 'users_project#update', on: :collection
    patch 'update_admin', to: 'users_project#update_admin', on: :collection
  end

  resources :noa_weather_stations do
    get 'start_import', on: :collection
  end

  resources :inmet_weather_stations do 
    get 'start_import', on: :collection
    get 'start_import_data', on: :collection
  end

  devise_for :users


  resources :dashboard do
    get 'grafico', on: :collection
  end

  resources :log_erros

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/inmet_weather_station.rb
class InmetWeatherStation < ApplicationRecord
  include Filterable
  include EstadoHelper

  self.primary_key = 'cdg_estacao'

  # scopes
  scope :by_cidade, ->(params) { where(cidade: params) }
  scope :by_cdg_estacao, ->(params) { where(cdg_estacao: params) }
  scope :by_nme_estado, ->(params) { where(nme_estado: params) }
  scope :by_situacao, ->(params) { where(situacao: params) }

  #actions
  before_create :type_regiao

  # methods class
  def self.inport_create(data)
    InmetWeatherStation.create(
      cidade: data['DC_NOME'],
      situacao: data['CD_SITUACAO'],
      sg_estado: data['SG_ESTADO'],
      vl_latitude: data['VL_LATITUDE'],
      vl_altitude: data['VL_ALTITUDE'],
      cdg_estacao: data['CD_ESTACAO'],
      vl_longitude: data['VL_LONGITUDE'],
      dta_inicio_operacao: data['DT_INICIO_OPERACAO']
    )
  end

  def self.inport_update(obj, data)
    obj.update(
      cidade: data['DC_NOME'],
      situacao: data['CD_SITUACAO'],
      sg_estado: data['SG_ESTADO'],
      vl_latitude: data['VL_LATITUDE'],
      vl_altitude: data['VL_ALTITUDE'],
      cdg_estacao: data['CD_ESTACAO'],
      vl_longitude: data['VL_LONGITUDE'],
      dta_inicio_operacao: data['DT_INICIO_OPERACAO']
    )
  end

  def self.find_create_or_update(data)
    obj = InmetWeatherStation.find_by(cdg_estacao: data['CD_ESTACAO'])
    
    if obj.present?
      inport_update(obj, data)
    else
      inport_create(data)
    end
  end

  def status?
    if self.status.to_i == 0
      return '<span class="badge text-bg-info">Ausente</span>'.html_safe
    elsif self.status.to_i == 1
      return '<span class="badge text-bg-warning">Aguardando</span>'.html_safe
    elsif self.status.to_i == 2
      return '<span class="badge text-bg-danger">Importando</span> '.html_safe
    elsif self.status.to_i == 3
      return '<span class="badge text-bg-success">Importado</span>'.html_safe
    elsif self.status.to_i == 4
      return '<span class="badge text-bg-warning">Atualizar!</span>'.html_safe
    end
  end

end

app/controllers/inmet_weather_stations_controller.rb
class InmetWeatherStationsController < ApplicationController
  before_action :set_weather_station, only: %i[ show edit update destroy ]
  before_action :set_filter_index, only: %i[index]

  # GET /weather_stations or /weather_stations.json
  def index
    @weather_stations = InmetWeatherStation
                          .filter(filters_params)
                          .paginate(page: params[:page], per_page: 20)
                          .order("cdg_estacao ASC")
  end

  # GET /weather_stations/1 or /weather_stations/1.json
  def show
  end

  # GET /weather_stations/new
  def new
    @weather_station = InmetWeatherStation.new
  end

  # GET /weather_stations/1/edit
  def edit
  end

  # POST /weather_stations or /weather_stations.json
  def create
    @weather_station = InmetWeatherStation.new(weather_station_params)

    respond_to do |format|
      if @weather_station.save
        format.html { redirect_to weather_station_url(@weather_station), notice: "Weather station was successfully created." }
        format.json { render :show, status: :created, location: @weather_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_stations/1 or /weather_stations/1.json
  def update
    respond_to do |format|
      if @weather_station.update(weather_station_params)
        format.html { redirect_to weather_station_url(@weather_station), notice: "Weather station was successfully updated." }
        format.json { render :show, status: :ok, location: @weather_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_stations/1 or /weather_stations/1.json
  def destroy
    @weather_station.destroy

    respond_to do |format|
      format.html { redirect_to weather_stations_url, notice: "Weather station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_filter_index
    @station = InmetWeatherStation.all
    @cidade = @station.collect{ |t| t.cidade }.uniq
    @wmo = @station.collect{ |t| t.cdg_estacao }.uniq
    @estado = @station.collect{ |t| t.nme_estado }.uniq

    @fiters_params = filters_params
  end

  def start_import
    ImportStationInmetWorker.perform_async();

    respond_to do |format|
      format.json { render json: { message: 'Importação em Andamento.' }, status: :ok }
    end
  end

  def start_import_data
    respond_to do |format|
      if params[:id_stattion].present? && InmetWeatherStation.find_by(cdg_estacao: params[:id_stattion]).present?
        DataImportScheduleInmetWorker.perform_async(params[:id_stattion]);
        InmetWeatherStation.find(params[:id_stattion]).update(status: 1);
        format.json { render json: { message: 'Importação da Estação em Andamento.' }, status: :ok }
      else
        format.json { render json: { message: 'Deve informar o Id da Estação' }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_station
      @weather_station = InmetWeatherStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weather_station_params
      params.require(:weather_station).permit(:cidade, :sg_estado, :situacao, :vl_latitude, :vl_longitude, :vl_altitude, :dta_inicio_operacao, :cdg_estacao)
    end

    def filters_params
      params.permit( :by_cdg_estacao, :by_cidade, :by_nme_estado, :by_situacao )
    end
end

app/helpers/inmet_weather_stations_helper.rb
module InmetWeatherStationsHelper
end

app/views/inmet_weather_stations/_form.html.erb
<%= form_with(model: weather_station) do |form| %>
  <% if weather_station.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weather_station.errors.count, "error") %> prohibited this weather_station from being saved:</h2>

      <ul>
        <% weather_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cidade, style: "display: block" %>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :sg_estado, style: "display: block" %>
    <%= form.text_field :sg_estado %>
  </div>

  <div>
    <%= form.label :situacao, style: "display: block" %>
    <%= form.text_field :situacao %>
  </div>

  <div>
    <%= form.label :vl_latitude, style: "display: block" %>
    <%= form.text_field :vl_latitude %>
  </div>

  <div>
    <%= form.label :vl_longitude, style: "display: block" %>
    <%= form.text_field :vl_longitude %>
  </div>

  <div>
    <%= form.label :vl_altitude, style: "display: block" %>
    <%= form.text_field :vl_altitude %>
  </div>

  <div>
    <%= form.label :dta_inicio_operacao, style: "display: block" %>
    <%= form.date_field :dta_inicio_operacao %>
  </div>

  <div>
    <%= form.label :cdg_estacao, style: "display: block" %>
    <%= form.text_field :cdg_estacao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inmet_weather_stations/edit.html.erb
<h1>Editing weather station</h1>

<%= render "form", weather_station: @weather_station %>

<br>

<div>
  <%= link_to "Show this weather station", @weather_station %> |
  <%= link_to "Back to weather stations", inmet_weather_stations_path %>
</div>

app/views/inmet_weather_stations/index.html.erb
<section class="background-radial-gradient overflow-hidden">

  <div style="height: 100vh;overflow-x: auto;">
    <div style="height: 100vh; padding: 30px 10px 10px 50px">

      <div>
        <div class="card">
          <div class="card-header pb-0" style="display: flex;">
            <h1>Estações Meteorológicas</h1>
            <button class='btn btn-primary btn-block' onclick= "submit_import_station()" style="margin-left: auto;margin-bottom: 11px;"> Gerar Importação </button>
          </div>
          <div class="card-body">

            <%= form_with(url: inmet_weather_stations_path, method: :get) do |form| %>
              <div class="row p-4">
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Código</p>
                  <%= form.select :by_cdg_estacao,
                                  options_for_select(@wmo.collect { |tp| [tp,tp] }, @fiters_params[:by_cdg_estacao]),
                                  {include_blank: 'Selecione'},
                                  {class: 'select2 form-control'} %>
                </div>

                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Cidade</p>
                  <%= form.select :by_cidade, options_for_select(@cidade.collect { |tp| [tp, tp] }, @fiters_params[:by_cidade]),
                                  {include_blank: 'Selecione um Cidade'}, {class: 'select2 form-control '} %>
                </div>
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Estado</p>
                  <%= form.select :by_nme_estado, options_for_select(@estado.collect { |tp| [tp, tp] }, @fiters_params[:by_nme_estado]),
                                  {include_blank: 'Selecione um Estado'}, {class: 'select2 form-control '} %>
                </div>
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Situação</p>
                  <%= form.select :by_situacao, options_for_select(["Pane", "Operante"], @fiters_params[:by_situacao]),
                                  {include_blank: 'Selecione um Situação'}, {class: 'select2 form-control '} %>
                </div>


                <div class="p-1 mt-5" style="justify-content: flex-end;display: flex;">
                  <%= form.submit "Filtrar", class: 'btn btn-primary btn-block mb-4', style:'width: 179px;'%>
                </div>

              </div>
            <% end %>

          </div>
        </div>
      </div>

      <div id="">


        <div class="card">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover table-sm">
              <thead class="thead-dark">
              <tr>
                <th scope="col">Código</th>
                <th scope="col">Cidade</th>
<!--                <th scope="col">Sigla Estado</th>-->
                <th scope="col">Estado</th>
                <th scope="col">Região</th>
                <th scope="col">Latitude</th>
                <th scope="col">Longitude</th>
                <th scope="col">Altitude</th>
                <th scope="col">Situação</th>
                <th scope="col">Dta Fundação</th>
                <th scope="col">Dta Fim Operação</th>
                <th scope="col">Status</th>
                <% if current_user.admin %>
                  <th scope="col">Opção</th>
                <% end %>
              </tr>
              </thead>
              <tbody>
                <% @weather_stations.each do |weather_station| %>
                  <tr id="station_<%= weather_station.id %>">
                    <td><%= weather_station.cdg_estacao %></td>
                    <td><%= weather_station.cidade %></td>
<!--                    <td><%#= weather_station.sg_estado %></td>-->
                    <td><%= weather_station.nme_estado %></td>
                    <td><%= weather_station.cdg_regiao %></td>

                    <td><%= weather_station.vl_latitude %></td>
                    <td><%= weather_station.vl_longitude %></td>
                    <td><%= weather_station.vl_altitude %></td>

                    <td><%= weather_station.situacao %></td>

                    <td><%= weather_station.dta_inicio_operacao.to_date_b %></td>

                    <td><%# weather_station.dta_fim_operacao.to_date_b %></td>
                    <td><%=  weather_station.status?  %></td>
                    <td>
                      <% if weather_station.status == 0 && current_user.admin %>
                        <%= "<button class='btn btn-primary btn-block padding-border-my' onclick= submit_import_data('#{weather_station.id}') > Importar </button>".html_safe %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
            <div style="display: flex;justify-content: center;">
              <%= will_paginate @weather_stations, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>


          </div>
        </div>

      </div>
    </div>
  </div>

</section>
<script>
  function submit_import_station() {
    $.ajax({
      url: "<%= start_import_inmet_weather_stations_path %>",
      type: "get",
      data: { },
      success: function (data) {
        console.log(data);
        Swal.fire({
          icon: 'success',
          title: data.message
        })
      },
      error: function (data) { },
    });
  }

  function submit_import_data(id_stattion) {
    $.ajax({
      url: "<%= start_import_data_inmet_weather_stations_path %>",
      type: "get",
      data: {id_stattion},
      success: function (data) {
        console.log(data);
        Swal.fire({
          icon: 'success',
          title: data.message
        })
      },
      error: function (data) { 
        Swal.fire({
          icon: 'dange',
          title: data.message
        })
      },
    });
  }

</script>

app/views/inmet_weather_stations/new.html.erb
<h1>New weather station</h1>

<%= render "form", weather_station: @weather_station %>

<br>

<div>
  <%= link_to "Back to weather stations", inmet_weather_stations_path %>
</div>

app/views/inmet_weather_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weather_station %>

<div>
  <%= link_to "Edit this weather station", edit_weather_station_path(@weather_station) %> |
  <%= link_to "Back to weather stations", inmet_weather_stations_path %>

  <%= button_to "Destroy this weather station", @weather_station, method: :delete %>
</div>