config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :inmet_weather_data
  mount Sidekiq::Web => '/sidekiq'

  resources :users_project, only: [:index, :create, :destroy, :show] do
    patch 'update_user', to: 'users_project#update', on: :collection
    patch 'update_admin', to: 'users_project#update_admin', on: :collection
  end

  resources :noa_weather_stations do
    get 'start_import', on: :collection
  end

  resources :inmet_weather_stations do 
    get 'start_import', on: :collection
    get 'start_import_data', on: :collection
  end

  devise_for :users


  resources :dashboard do
    get 'grafico', on: :collection
  end

  resources :log_erros

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/weather_station.rb
class WeatherStation < ApplicationRecord
  include Filterable

  scope :by_cidade, ->(params) { where(cidade: params) }
  scope :by_cdg_estacao, ->(params) { where(cdg_estacao: params) }
  scope :by_nme_estado, ->(params) { where(nme_estado: params) }
  scope :by_situacao, ->(params) { where(situacao: params) }
end

app/controllers/weather_stations_controller.rb
class WeatherStationsController < ApplicationController
  before_action :set_weather_station, only: %i[ show edit update destroy ]
  before_action :set_filter_index, only: %i[index]

  # GET /weather_stations or /weather_stations.json
  def index
    @weather_stations = WeatherStation
                          .filter(filters_params)
                          .paginate(page: params[:page], per_page: 20)
                          .order("sg_estado ASC, cidade ASC")
  end

  # GET /weather_stations/1 or /weather_stations/1.json
  def show
  end

  # GET /weather_stations/new
  def new
    @weather_station = WeatherStation.new
  end

  # GET /weather_stations/1/edit
  def edit
  end

  # POST /weather_stations or /weather_stations.json
  def create
    @weather_station = WeatherStation.new(weather_station_params)

    respond_to do |format|
      if @weather_station.save
        format.html { redirect_to weather_station_url(@weather_station), notice: "Weather station was successfully created." }
        format.json { render :show, status: :created, location: @weather_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_stations/1 or /weather_stations/1.json
  def update
    respond_to do |format|
      if @weather_station.update(weather_station_params)
        format.html { redirect_to weather_station_url(@weather_station), notice: "Weather station was successfully updated." }
        format.json { render :show, status: :ok, location: @weather_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_stations/1 or /weather_stations/1.json
  def destroy
    @weather_station.destroy

    respond_to do |format|
      format.html { redirect_to weather_stations_url, notice: "Weather station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_filter_index
    @station = WeatherStation.all
    @cidade = @station.collect{ |t| t.cidade }.uniq
    @wmo = @station.collect{ |t| t.cdg_estacao }.uniq
    @estado = @station.collect{ |t| t.nme_estado }.uniq

    @fiters_params = filters_params
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_station
      @weather_station = WeatherStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weather_station_params
      params.require(:weather_station).permit(:cidade, :sg_estado, :situacao, :vl_latitude, :vl_longitude, :vl_altitude, :dta_inicio_operacao, :cdg_estacao)
    end

    def filters_params
      params.permit( :by_cdg_estacao, :by_cidade, :by_nme_estado, :by_situacao )
    end
end

app/views/weather_stations/edit.html.erb
<h1>Editing weather station</h1>

<%= render "form", weather_station: @weather_station %>

<br>

<div>
  <%= link_to "Show this weather station", @weather_station %> |
  <%= link_to "Back to weather stations", weather_stations_path %>
</div>

app/views/weather_stations/index.html.erb
<section class="background-radial-gradient overflow-hidden">

  <div style="height: 100vh;overflow-x: auto;">
    <div style="height: 100vh; padding: 30px 10px 10px 50px">

      <div>
        <div class="card">
          <div class="card-header pb-0">
            <h1>Estações Meteorológicas</h1>
          </div>
          <div class="card-body">

            <%= form_with(url: weather_stations_path, method: :get) do |form| %>
              <div class="row p-4">
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Código</p>
                  <%= form.select :by_cdg_estacao,
                                  options_for_select(@wmo.collect { |tp| [tp,tp] }, @fiters_params[:by_cdg_estacao]),
                                  {include_blank: 'Selecione'},
                                  {class: 'select2 form-control'} %>
                </div>

                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Cidade</p>
                  <%= form.select :by_cidade, options_for_select(@cidade.collect { |tp| [tp, tp] }, @fiters_params[:by_cidade]),
                                  {include_blank: 'Selecione um Cidade'}, {class: 'select2 form-control '} %>
                </div>
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Estado</p>
                  <%= form.select :by_nme_estado, options_for_select(@estado.collect { |tp| [tp, tp] }, @fiters_params[:by_nme_estado]),
                                  {include_blank: 'Selecione um Estado'}, {class: 'select2 form-control '} %>
                </div>
                <div class="col-md-3">
                  <p class="mb-1 mt-3 font-weight-bold text-muted">Situação</p>
                  <%= form.select :by_situacao, options_for_select(["Pane", "Operante"], @fiters_params[:by_situacao]),
                                  {include_blank: 'Selecione um Situação'}, {class: 'select2 form-control '} %>
                </div>


                <div class="p-1 mt-5" style="justify-content: flex-end;display: flex;">
                  <%= form.submit "Filtrar", class: 'btn btn-primary btn-block mb-4', style:'width: 179px;'%>
                </div>

              </div>
            <% end %>

          </div>
        </div>
      </div>

      <div id="">


        <div class="card">
          <div class="card-body">

            <table class="table table-striped table-hover">
              <thead class="thead-dark">
              <tr>
                <th scope="col">Código</th>
                <th scope="col">Cidade</th>
                <th scope="col">Sigla Estado</th>
                <th scope="col">Estado</th>
                <th scope="col">Região</th>
                <th scope="col">Latitude</th>
                <th scope="col">Longitude</th>
                <th scope="col">Altitude</th>
                <th scope="col">Situação</th>
                <th scope="col">Dta Fundação</th>
              </tr>
              </thead>
              <tbody>
              <% @weather_stations.each do |weather_station| %>
                <%= render weather_station %>
              <% end %>
              </tbody>
            </table>

            <div style="display: flex;justify-content: center;">
              <%= will_paginate @weather_stations, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>


          </div>
        </div>

      </div>
    </div>
  </div>

</section>

<script>
    window.addEventListener('DOMContentLoaded', () => {
        $('.select2').select2();
    })
</script>

app/views/weather_stations/new.html.erb
<h1>New weather station</h1>

<%= render "form", weather_station: @weather_station %>

<br>

<div>
  <%= link_to "Back to weather stations", weather_stations_path %>
</div>

app/views/weather_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weather_station %>

<div>
  <%= link_to "Edit this weather station", edit_weather_station_path(@weather_station) %> |
  <%= link_to "Back to weather stations", weather_stations_path %>

  <%= button_to "Destroy this weather station", @weather_station, method: :delete %>
</div>